# 路径配置
paths:
  base_dir: "./config"  # 基础目录，使用当前项目目录
  data_dir: "./config/data"  # 数据目录
  log_dir: "./config/logs"  # 日志目录

# 爬虫配置
scrapers:
  timeout: 30
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  headers:
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    Accept-Language: "zh-CN,zh;q=0.9,en;q=0.8"

# 大模型配置
models:
  # 当前生效的大模型，可选值：openai, azure_openai, anthropic, baidu, ollama, siliconflow
  active_model: "siliconflow"
  openai:
    api_key: "your-openai-api-key"
    model: "gpt-4"
    temperature: 0.7
    max_tokens: 2000
  
  azure_openai:
    api_key: "your-azure-openai-api-key"
    endpoint: "https://your-resource-name.openai.azure.com/"
    deployment_name: "your-deployment-name"
    api_version: "2023-05-15"
    temperature: 0.7
    max_tokens: 2000
  
  anthropic:
    api_key: "your-anthropic-api-key"
    model: "claude-2"
    temperature: 0.7
    max_tokens: 2000
  
  baidu:
    api_key: "your-baidu-api-key"
    secret_key: "your-baidu-secret-key"
    temperature: 0.7
    max_tokens: 2000
    
  # Ollama本地模型配置
  ollama:
    base_url: "http://localhost:11434"  # Ollama API地址
    model: "llama2"                     # 使用的模型名称
    temperature: 0.7                    # 温度参数
    max_tokens: 2000                    # 最大生成令牌数
    
  # 硅基流动API配置
  siliconflow:
    api_key: "sk-fogunwxlgmrezxnysruwjofssgicbufgmnvskofdgvlsofvq"
    base_url: "https://api.siliconflow.cn/v1"
    model: "Qwen/QwQ-32B"
    temperature: 0.0
    max_tokens: 8192

# WordPress配置
wordpress:
  url: "https://your-wordpress-site.com/wp-json/wp/v2"
  username: "your-username"
  password: "your-password"
  categories: [1, 2]  # 分类ID
  tags: [3, 4]  # 标签ID
  status: "draft"  # draft, publish, private

# 命令行配置
cli:
  publish: false  # 是否发布到WordPress
  max_iterations: 3  # SEO优化最大迭代次数

# SEO配置
seo:
  min_word_count: 800
  keyword_density: 0.02
  meta_description_length: 160
  title_max_length: 60
  threshold: 80

# 内容质量配置
content_quality:
  min_readability_score: 60
  min_originality_score: 70
  max_avg_sentence_length: 25
  min_paragraph_count: 5
  threshold: 70